# Generated by Django 4.1.3 on 2022-11-05 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cta_receptora', models.BigIntegerField(max_length=20)),
                ('ref', models.CharField(max_length=10)),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('id_emisora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nrocuenta', models.BigIntegerField(max_length=20)),
                ('nombre_prop', models.CharField(max_length=25)),
                ('apell_prop', models.CharField(max_length=25)),
                ('cedula_prop', models.BigIntegerField(max_length=8)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
