# Generated by Django 4.1.3 on 2022-11-05 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_rename_user_id_cuentas_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuentas',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='transfers',
            old_name='emisora',
            new_name='id_emisora',
        ),
    ]
