# Generated by Django 4.1.3 on 2022-11-05 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_cuentas_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentas',
            name='cedula_prop',
        ),
        migrations.RemoveField(
            model_name='cuentas',
            name='nrocuenta',
        ),
        migrations.RemoveField(
            model_name='transfers',
            name='cta_receptora',
        ),
    ]
