# Generated by Django 4.1.3 on 2022-11-05 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfers',
            name='id_emisora',
        ),
        migrations.DeleteModel(
            name='Cuentas',
        ),
        migrations.DeleteModel(
            name='Transfers',
        ),
    ]
